name: "Build, inspect and scan a docker image"
description: "Building the docker image, inspect and scan it"
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host
    - name: Build the Docker image
      id: docker_test
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: localhost:5000/foobar/${{ env.IMAGE_NAME }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        build-args: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_VERSION="$(git describe --tags)"
          VCS_REF="$(git rev-parse --short HEAD)"
          VCS_URL="$(git config --get remote.origin.url)"
          VCS_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    - name: Inspect the Docker image
      run: |
        docker buildx imagetools inspect localhost:5000/foobar/${{ env.IMAGE_NAME }}
    - name: Scan image with Container Scan
      uses: Azure/container-scan@v0
      env:
        DOCKER_CONTENT_TRUST: 1
      with:
        image-name: localhost:5000/foobar/${{ env.IMAGE_NAME }}
        severity-threshold: HIGH
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: localhost:5000/foobar/${{ env.IMAGE_NAME }}
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      uses: anchore/scan-action@main
      with:
        image: localhost:5000/foobar/${{ env.IMAGE_NAME }}
        acs-report-enable: true
    - name: Move reports
      run: mkdir -p sarif-reports && cp *results.sarif sarif-reports/
    - name: Upload Reports
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'sarif-reports'
